/opt/etherlab/lib
/opt/epics/base/lib/linux-x86_64
/opt/epics/support/asyn/lib/linux-x86_64
/opt/epics/support/motor/lib/linux-x86_64
/opt/epics/support/ecmc/lib/linux-x86_64
/opt/epics/support/ecmc/ecmcExampleTop/lib/linux-x86_64
/opt/epics/support/ruckig/build
